### PR TITLE
chore: update annotations

### PR DESCRIPTION
**Pull request by aarnphm**
Fix bad merge and update annotations from #288

Address comments type syntax to newer syntax.

### CODE REVIEW

**Comment by aarnphm** [comment]
cc @Tinche

**Comment by Tinche** [comment]
Thanks!

**Comment by phiresky** [comment]
This change results in the following mypy error in my dependent project:

```
>>>> Running mypy...
.venv/lib/python3.10/site-packages/cattrs/converters.py:541: error: Invalid "type: ignore" comment
Found 1 error in 1 file (errors prevented further checking)
```
